### ISSUE TITLE
[Unit 4][Topic]: Standards and Guidelines - Principles of Accessible Design

### ISSUE THREAD

**Issue by AndrewArch** [w3c/wai-curricula#107]
Homework calls for an understanding of Guidelines and SC yet this first topic has only introduced the Principles (POUR).

**Comment by daniel-montalvo** [comment]
Hey andrew:

Thanks for commenting on this.

I am assuming you are referring specifically to:

> * Ask students to write a short essay commenting on the four principles of web accessibility and their corresponding guidelines.

which might well be understood as the success criteria.

For this first topic we have made some changes in the [Live draft](https://deploy-preview-72--wai-curricula.netlify.com/curricula/1-4/)

In the first topic we talk now about examples rather than guidelines, requirements,  or success criteria.

So we could adapt this homework idea to something like:

> * Ask students to write a short essay commenting on the four principles of web accessibility and to give examples in websites they know about.

Would that change address the issue?

**Comment by nitedog** [comment]
Not sure I agree with "essay". To me an essay has a fairy scientific or at least methodological approach (describing a problem/challenge, discussing it, etc.). Not sure what to expect in such a write-up either (essay or not) -- I do not understand how to carry this out (as instructor or student).

**Comment by daniel-montalvo** [comment]
These ideas have been modified. I replaced essays with reports and quizzes instead to broaden scope.
