### ISSUE TITLE
[high] modules and units naming confusion with W3Cx/edX

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-curricula#117]
I don't have it handy to confirm, yet I think W3Cx/edX HTML5 courses use "module" for what our curricula calls "unit". Since we use "module" differently and are doing a W3Cx/edX MOOC, this could be especially confusing. :(

**Comment by shawna-slh** [comment]
Hi @daniel-montalvo & @nitedog 

I'm feeling even more strongly about this now.

At first I was thinking it would mostly just be confusing for those trainers and EOWG participants creating and/or reviewing both.

Now I'm thinking that many potential trainers will hopefully use the curricula ***and*** go through the edX/W3Cx MOOC to get ideas -- and maybe even directly use some of the MOOC materials in their courses.

For this reason, I think it's important that we better align the terminology between the curricula and the MOOC.

**Comment by nitedog** [comment]
I don't feel strongly about the terminology we use but not convinced it is as big of an issue. Happy to discuss further.
AFAIK, edX does not use/define the term "module". Some W3Cx courses chose to use that term in a particular way. Other courses use this or other terminology differently, and there does not seem to be one commonly agreed on definition. The upcoming W3Cx course on accessibility will *not* use that term, so the above scenario of someone using both the curricula and the course is not applicable in my view. Not sure there is any terminology that is conflict-free but happy to further discuss benefits of changing the current terminology.

**Comment by nitedog** [comment]
New information: The W3Cx course "Introduction to Web Accessibility" may actually use "module" in the same way other W3Cx courses, so we would end up with conflicting terminology. We do need to change our terminology, unfortunately.

**Comment by daniel-montalvo** [comment]
If we take the [HTML5 and CSS Fundamentals](https://www.edx.org/course/html5-and-css-fundamentals-3) W3Cx course as an example, we can infer some differences in terminology between WAI Curricula and W3Cx.

WAI Curricula | W3Cx
----- | -----
Module | Course
Unit | Module
Topic | [No equivalent]

We have several options here:

1. Stop using the word "unit", and change "module" to coincide with the meaning in W3cX. This way, we would have:
    * Introduction to Web Accessibility
      * Module 1: What is Web Accessibility.
      * Module 2: People and Digital Technology.
      * And so on.

  For the remaining instances of the word "module" as it's been used in the resource up to now, we could change them to "curriculum (a singular form in a group of curricula). We would have:
  * "Curriculum: Introduction to Web Accessibility" Previously "module"
    * "This curriculum provides a general introduction to web accessibility. It is designed for any students with basic understanding of computers and the Web". Previously "This module ...".

2. Not using "module" and "unit" at all, an changing these words to another synonyms. We would have:
    * Section: Introduction to Web Accessibility
      * Subsection 1: What is Web Accessibility.
      * Subsection 2: People and Digital Technology.
      * And so on.

I prefer the first of the options. We make easy for people who want to use both resources to establish the similarities between them. If we add other different terms such as section, subsection, lesson, or syllabus, we would not conflict with W3CX but we would add unnecessary information and people who want to use these two resource would still need to infer the meaning for our terminology and that from W3Cx.

**Comment by bakkenb** [comment]
I almost like leaving it as is. The way we have it now indicates that these are NOT courses, but modules, units, or topics that can be implemented, in part or whole, anywhere in anyone course or training. I worry that changing it to Option 1...

> Stop using the word "unit", and change "module" to coincide with the meaning in W3cX. This way, we would have:
> Introduction to Web Accessibility
> - Module 1: What is Web Accessibility.
> - Module 2: People and Digital Technology.
> - And so on.

... would make this format seem too much like a course. I think we don't want to convey that in any way.

I don't like Option 2 as it removes any ability for others to refer to parts of our curricula in conversation or communication. I would rather use our current system where people can then communicate like this, "From Module 1, let's include Unit 3, topics 1 and 4, and also all of Unit 4 in our course." . . . Instead of forcing confusing communication like this, "From Section 1, let's include Subsection 3, sub-subsections 1 and 4, and also all of subsection 4 in our course."

I vote to leave it as it currently is.

**Comment by nitedog** [comment]
@bakkenb currently we use "Unit 1: What is Web Accessibility [...]", so to me there is no big difference to use "Module 1: What is Web Accessibility [...]" instead. I think @daniel-montalvo is right -- we currently hardly use the term "module", so referring to that as "curriculum" instead (with "curricula" being the entire set of all "curriculums" we plan) seems to be a fairly simple way to align with W3Cx.

**Comment by daniel-montalvo** [comment]
AS per EO 15th November minutes at https://www.w3.org/2019/11/15-eo-minutes.html

* Where we used "units" we will use "Modules".
* "Where we had "modules" (a single curriculum:
  * For the title "Module: Introduction to Web Accessibility" we will use just "Introduction to Web Accessibility".
  * For the rest of the instances of the word "module" in its previous meaning, we decided we don't have too much of  a problem there as long as we avoid using "Course" as a replacement. We are now using "Curriculum" five times at https://www.w3.org/WAI/curricula/ and at https://www.w3.org/WAI/curricula/introduction-to-web-accessibility/. This is because we need to define the structure and clearly distinguish the whole work that is envisioned from the current piece that is drafted.

Closing this. Feel free to reopen if needed.
