### ISSUE TITLE
It is not clear to screenreaders table modules (Curricula Modules)

### ISSUE THREAD

**Issue by Inclusive-it** [w3c/wai-curricula#120]
It is very difficult to navigate at work with screenreaders. Testers do not understand the module to which the rate applies.

**Comment by daniel-montalvo** [comment]
Hi:

I don't really understand what you mean when you say 

> It is very difficult to navigate at work with screenreaders. Testers do not understand the module to which the rate applies.

By rate, do you mean the levels (Basic, Intermediate, and Advanced)?

If so, you can move left, right, up, and downwards through the table holding down CTRL+Shift and then using the left, right, up, and down arrow keys respectively. The left column contains the different levels, so each row will correspond to each of the levels outlined.

Would you please clarify on this issue so that we can figure out a fix for it?

**Comment by daniel-montalvo** [comment]
Added explanatory paragraph as well as table summary and caption.

Closing, feel free to come back if you want to provide further input.
