### ISSUE TITLE
[super minor] [First Page] Structure, missing content

### ISSUE THREAD

**Issue by yatil** [w3c/wai-curricula#134]
I think it would be good to use headings instead of a nested list for the structure. Alternatively a description list?

In the table there are ??? And @@@ to signal undecided stuff. We usually don’t publish work in progress on our site. I personally would prefer to remove what we’re not ready to talk about yet.

I feel uneasy making promises. 

We at least need to be clear on what we’re working on when and what those symbols mean.

**Comment by daniel-montalvo** [comment]
This section is thought to be an outline of:
1. What we already have (first module).
2. What is to come, which is still not developed. We don't have started working on most of these yet, so probably what is there might change in the future when we start developing it. Should we not mention any of the work that is still to do?

I think we should. This is the opening page and we want to provide the reader with the necessary information and context to understand this resource. My proposal would be to:

1. Add information in the heading. Instead of "Curricula Modules" we might have "Outline of Curricula Modules".
2. Add a short paragraph before the table indicating that drafted modules are linked and that the rest of the outlined modules are ideas still under analysis.
3. Remove the @@ and.

Would the above address your issue?

Thanks.

**Comment by yatil** [comment]
I’m not 100% confident publishing “what is to come”, but I don’t object. The rest of the proposal is good for me.

**Comment by daniel-montalvo** [comment]
Hi Eric:

Thanks for your feedback.

At https://deploy-preview-132--wai-curricula.netlify.com/curricula/ I have made some changes:

* Updating the heading title to "Future Outline", so that it is clear from the beginning that we are referring to resources that are yet to come.
* Adding a new paragraph explaining the current status of the resource, clarifying what we have already and what we plan to have. It looks as follows:
    > The table below shows how this resource could address different roles. 
Currently only the first curriculum "Introduction to Web Accessibility" 
is available. Other curricula will follow, and will be linked from here.

It is true that we do not usually publish "future plans" that are still under analysis but, in this case, we do have the resources and commitment to develop it. Also, I see this future outline as a way of involving other audiences from the community to engage with us, i.e., entities looking for authoritative training resources that they can rely on. We are basically saying "Stay tuned because this portion that we have developed now is the opening door to the rest of the work that can be done here".
