### ISSUE TITLE
[Ed-Med] Unclear teaching idea

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-curricula#155]
In Principles, Standards, and Checks, Principles of Web Accessibility, Teaching Ideas:

> * Reflect with students on which of these principles relate more to their daily tasks or activities and how they could apply such principles in their daily life.

I am not sure what this means or how I might use it in a course.

**Comment by daniel-montalvo** [comment]
This teaching idea intended to anticipate Roles and Responsibilities (one of the topics in Module 5), so that instructors could establish links between principles and tasks in the design and development process. Mapping a principle (with its whole set of requirements) to one or more roles might not be accurate, but asking instructors to introduce the need for a variety of roles to meet accessibility requirements could be more tangible. This is then extended in [Topic: Roles and Responsibilities](https://wai-curricula.netlify.com/curricula/introduction-to-web-accessibility/getting-started-with-accessibility/#topic-roles-and-responsibilities). Changed in ebb9b01 to:

> * Mention that meeting accessibility requirements needs involvement from a variety of roles in the design and development process.

**Comment by iadawn** [comment]
Could you make it more explicit that it relates to that shared ownership of the work?

For example:

> * Introduce and explore how different design and development roles have responsibility for different parts of each principle.

**Comment by daniel-montalvo** [comment]
Thanks, I will take it, except for the "explore" addition. I don't think it is time to explore these responsibilities yet but just to give a bit of a hint. That is scheduled for module 5, where they will go through the [ARRM document](https://www.w3.org/WAI/EO/wiki/Role_definition_document).

Would it be OK to say:

> * Introduce how different design and development roles have responsibility for different parts of each principle.

?

**Comment by iadawn** [comment]
That is fine.
