### ISSUE TITLE
[ED-low] W3C Process?

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-curricula#160]
I don't see the relevance to this work of the W3C process in developing standards. It seems more bureaucratic fact rather than helpful knowledge, not really applicable in any way. It seems to clutter the module and my preference would be to remove it or at least make it an optional section.  There are ways to "Explain that WAI develops these standards following the W3C process, with involvement of people with disabilities, industry, public, and research bodies, and individual experts" without going through the process document.

**Comment by daniel-montalvo** [comment]
Hey @sharronrush 

Thanks for your feedback. I am not sure that removing this resource completely is a good idea, it may have an impact on the work that @nitedog is coordinating in the MOOC. I would agree to make it less relevant.

Proposal:

Remove "Go through the milestones in WAI's standards development. Refer to [How WAI Develops Accessibility Standards through the W3C Process](/standards-guidelines/w3c-process/)", but keep the teaching resource at the end of the list, so that people can still recognize it as a possible resource to create their course(s).

If @nitedog suggests removing it completely would not affect the work on the MOOC, we could go for it.

**Comment by nitedog** [comment]
This is independent of any work on the MOOC. No need to conflate the two efforts.

I agree that this sentence seems oddly placed. Also, I agree that the emphasis of this should be on the broad involvement of different stakeholders in a rigorous development process (as @sharronrush  seems to suggest) rather than on the milestones themselves. Indeed, that would seem too bureaucratic.

How about editing the sentence accordingly and moving it to the learning outcomes below?

**Comment by daniel-montalvo** [comment]
We have now removed the whole sentence.

We have a learning outcome that focuses on the broad involvement of different stakeholders that states:

> * Describe how and why the public approach of standards development involves people with disabilities, industry, public bodies, and other individuals. 

And a teaching idea to deliver it:

> * Explain that WAI develops these standards following the W3C process, with involvement of people with disabilities, industry, public, and research bodies, and individual experts. Refer to How WAI Develops Accessibility Standards through the W3C Process:
Milestones and Opportunities to Contribute page, [Community Colaboration Section](/standards-guidelines/w3c-process/#community).

Closing, feel free to reopen if necessary.
