### ISSUE TITLE
Proposal to fix issues related to Outline table

### ISSUE THREAD

**Issue by daniel-montalvo** [w3c/wai-curricula#166]
The table in the opening page for the [WAI-Curricula](https://www.w3.org/WAI/curricula/#future-outline) has currently several open issues. You can have a look at issues #131, #133, and #137 for background on these discussions.

I have been working in a [proposal to resolve them](https://deploy-preview-165--wai-curricula.netlify.com/curricula/)

1. We would keep the table with the three rows: Basic, Intermediate, and Advanced.
2. We would strip the bullets with ideas for future modules and put them below the table as an expandable and collapsible section. 

With this:

1. We make the table smaller and easier to process.
2. We still give people the chance to have a look at the current ideas for possible modules below the table.

**Comment by eoncins** [comment]
I personally like the new proposal. It is easier to process.
Still, I think that is important to maintain an overview in order to help prospective trainers to choose modules according to their course needs. (i.e. a trainer might want to give a course and combine modules from intermediate designers and intermediate authors)
Is it foreseen that trainers can combine modules from different roles?

**Comment by daniel-montalvo** [comment]
> I personally like the new proposal. It is easier to process.

Good!

> Still, I think that is important to maintain an overview in order to help prospective trainers to choose modules according to their course needs. (i.e. a trainer might want to give a course and combine modules from intermediate designers and intermediate authors)
> Is it foreseen that trainers can combine modules from different roles?

Yes, IMO that should be doable, though it is difficult to conceptualize at this point when we have only the introduction curricula (which tries to address multiple audiences), but it is definitely something I think will be clearer as we add more modules.

When we define "module", we have:
> Modules &mdash; Smallest logical entity of a curriculum that is expected to be taught and assessed in its entirety.

But we don't say anything about whether or not we can combine modules from different curricula.

We could add this idea to the paragraph below the table where we introduce the different ideas we currently have. It currently states:

> The following shows possible modules for  each outlined curriculum.

and could be changed to:

> The following shows possible modules for  each outlined curriculum. You can combine them to address different roles in the same course.

What do you think?

**Comment by eoncins** [comment]
I agree.

**Comment by shawna-slh** [comment]
Summary from [EOWG minutes](https://www.w3.org/2019/12/13-eo-minutes.html#item04): The existing table (with all the data in it) is useful for target audience and main use cases.

**Comment by yatil** [comment]
I just saw the discussion in the minutes – it looks like the usefulness is the organization of the data, not necessarily the table. I think what we want here is a kind of interactive info graphic instead of a table. I think an information designer or content strategist might have good ideas to organize it.

**Comment by daniel-montalvo** [comment]
More table refinements have been made at
https://wai-curricula.netlify.com/curricula/

Closing as this proposal is now outdated.
