### ISSUE TITLE
[Modules 1 and 2] Order of success criteria in instructors competencies

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#205]
Success criteria are not ordered

Also "success criteria 2.4.5" should be "success criterion 2.4.5"

**Comment by daniel-montalvo** [comment]
These should now be ordered. Please note that there may be some that may be moved around due to the topic and module restructuring.

Please see:

-   [Competencies for Module 1: Structure, Semantics, and Navigation](https://deploy-preview-232--wai-curricula.netlify.app/curricula/developing-accessible-content/structure-semantics-and-navigation/#competencies).
-   [Competencies for Module 2: Navigational Menus](https://deploy-preview-232--wai-curricula.netlify.app/curricula/developing-accessible-content/navigational-menus/#competencies).
