### ISSUE TITLE
[Module 2 Navigation and Menus] Title "Meta Information for a Navigational Mechanism"

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#209]
This title only conveys a subset of the content of the topic. Providing visual cues and ensuring there are no keyboard traps is not "meta information". I would even argue that the remainder of the mechanisms are "information" and not "meta information". 

I feel this topic needs a better name. I've been trying to come up with one, but I haven't been really successful.

**Comment by sloandr** [comment]
I agree, and looking at the listed learning outcomes for this topic, it seems that it's introducing some core principles of accessible navigation (focus indication, focus order, no keyboard trap, identify current location in a series), so perhaps the topic title should emphasis this? I'd also suggest it should appear earlier in the list of topics covered.

If this topic covers keyboard traps (a dynamic component of navigation rather than specifically related to markup), then should it also cover ensuring keyboard operability, addressing how to meet SC 2.1.1. explicitly? I maybe missed it, but I don't see that called out anywhere else in the module.

**Comment by daniel-montalvo** [comment]
Hello @carlosapaduarte 

Part of the content covered in this topic has been moved to:
[Topic Page Structure](https://wai-curricula.netlify.com/curricula/developing-accessible-content/structure-and-semantics/#topic-page-structure)

I think we now convey focus indicators, meaningful sequence, page titles, and page language mor clearly. But it is true that, as @sloandr  suggests, we may be missing a more explicit coverage for keyboard navigation.

In this other [version of Topic Page Structure](https://deploy-preview-242--wai-curricula.netlify.com/curricula/developing-accessible-content/structure-and-semantics/#topic-page-structure), preview from #242 I have:

* added explicit mention to keyboard-only users
* added SC 2.1.1 Keyboard to module 1

For further discussion is if we still need a more clear coverage of keyboard navigation.

**Comment by daniel-montalvo** [comment]
Discussed in
https://www.w3.org/2020/08/25-wai-curricula-minutes.html#item02
