### ISSUE TITLE
[all] overall title front-loading

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-curricula#216]
Current title is:
> Curricula on Web Accessibility: A Framework to Build Your Own Courses

Front-loading with "Curricula" I think is good within the context of the WAI website.

However, **thinking of all the other places where hopefully people will refer to it &mdash; lists of resources for instructors, in sentence in blogs, etc.** &mdash; I wonder if it we be better front-loaded with "Web Accessibility"?

> Web Accessibility Curricula: A Framework to Build Your Own Courses

(I don't feel strongly either way.)

(Apologies if this was already addressed previously.)

**Comment by daniel-montalvo** [comment]
I don't feel strongly either way, each has its own pros and cons.

Whereas I do think we would need to take a decision before publishing this specific curriculum, would you mind if we move this down in our prioritization until we address other more complicated issues?

**Comment by shawna-slh** [comment]
> we would need to take a decision before publishing this specific curriculum, would you mind if we move this down in our prioritization

sure, no problem at all

**Comment by shawna-slh** [comment]
After more thought, I still don't feel strongly.

Yet, I'm thinking it would be good to get other perspectives. Maybe folks can share other use cases that would help make the decision easier?

How about asking the Task Force and EOWG to comment on this issue?

**Comment by bakkenb** [comment]
From just the title point of view (and not thinking about curricula, modules, objectives, etc. ...

I prefer the current title. To me it implies that this is a set of curricula that is about web accessibility, not the only curricula, but the WAI curricula, and people can choose to use it to fit there need for multiple purposes.

The proposed title to me sounds more like a defined course that should be used exactly how presented.

**Comment by daniel-montalvo** [comment]
#### Curricula on Web Accessibility

- Pros:
  - Front-loads type of resource
  - Helps identify resource in the context of WAI website.
- Cons:
  - Longer phrase.
  - Hides relevant info when referenced from curricula specific sites or from outside WAI resource.

#### Web Accessibility Curricula

- Pros
  - Identifies type of curricula outside WAI website.
  - Shortens out the sentence a bit
- Cons:
  - Could be perceived as a specific course with already fixed name.
  - Would be distracting for those already used to current title

#### Use Cases

- I am using the curricula to build my course. I move back and forth between the curricula and the proposed teaching resources. I find it useful to have the word "curricula" up-front so that I now at a glance where I am on WAI website.
- I am comparing  different curricula to include different contents: accessibility, development, UX design, etc. "Curricula on" annoys me a bit, since I already know I am dealing with curricula. Having "Web Accessibility" at the beginning would help me know which of the curricula resource I am in much quicker.

**Comment by daniel-montalvo** [comment]
We will keep title as is, as discussed in [EOWG meeting 5 Feb](https://www.w3.org/2021/02/05-eo-minutes.html#t01)
