### ISSUE TITLE
[Unit 5]: Reconsidering the Title (was Applying and Managing Accessibility)

### ISSUE THREAD

**Issue by daniel-montalvo** [w3c/wai-curricula#26]
In [F2F EOWG meeting](https://www.w3.org/2019/05/13-eo-minutes.html), we discussed the title for Unit 5. We started with "Getting Started with Accessibility" which left some of the planning stages behind. Then we have "Applying and Managing accessibility", but it seems it overlaps with the first of the topics, called "Planning and Managing". What is a good title for unit 5 for you, given the current contents?

A couple of suggestions are:
* "Managing Web Accessibility", assuming with "Managing" we are covering "planning" and "Applying" stages.
* "Planning Web Accessibility" since this unit has ended up concentrating more on planing aspects than on actual managing stages.
* "Implementing Web Accessibility" thanks to @vmmiller

**Comment by yatil** [comment]
Editor’s discretion from me.

**Comment by vmmiller** [comment]
Editor's discretion but just throwing in an idea:  "Implementing Web Accessibility"

**Comment by JenniferChadwick** [comment]
Editor's discretion, however, I'm a fan of "Implementing Web Accessibility" as it communicates a process with an outcome.

**Comment by daniel-montalvo** [comment]
Thanks for this good suggestion @vmmiller  and @JenniferChadwick

**Comment by hidde** [comment]
+1 for “Implementing Web Accessibility”!

**Comment by Sylduch-Conseil** [comment]
Also +1 for implementing

**Comment by shawna-slh** [comment]
The topics in the [Unit](https://deploy-preview-29--wai-curricula.netlify.com/curricula/1-5/) are:
* Topic: Planning and Managing Web Accessibility
* Topic: Developing [Organizational] Policies and [Accessibility] Statements
* Topic: Roles and Responsibilities
* Topic: Accessibility in an Existing Project -- which is on [Web Accessibility First Aid: Approaches for Interim Repairs](https://www.w3.org/WAI/planning/interim-repairs/):
  * Identify the Issues
  * Consider the Scope
  * Set your Accessibility Target Level
  * Tips for Efficient Repair
  * Longer Term: Planning and Managing

To me that's not "Implementing". "Implementing" is actually doing it.

**Comment by bakkenb** [comment]
I am in agreement about hesitation to use "implementing" in the title of this unit. It seems that this just scratches the surface of any accessibility implementation in an organization. It could be misleading people to believe that this unit will have all the stages / strategies / concepts / tasks for implementing web accessibility, and it doesn't (it isn't intended to). So I think we need to keep looking for another title that is more fitting to the content. 

Some Ideas:
- "Getting Started with Web Accessibility"
- "The Beginnings of Web Accessibility"
- "Embarking on Web Accessibility"
- "Setting the Stage for Web Accessibility"

**Comment by shawna-slh** [comment]
**[EOWG Minutes from 2 August 2019](https://www.w3.org/2019/08/02-eo-minutes.html#item03) includes brainstorms**

**Comment by eoncins** [comment]
As part of the course, I think that it is important to keep a logical structure for the students/teachers. Unit 5 is the last unit and it is expected that students apply all the knowledge acquired in the other units. Is that right?

Introduction to Web Accessibility
UNIT 1.- What is Web Accessibility
UNIT 2.- People and Digital Technology
UNIT 3.- Business Case and Benefits
UNIT 4.- Standards and Guidelines
UNIT 5.- Applying and Managing Accessibility (in review)

I personally see the titles provided by @bakkenb and on the online meeting (I really like most of them), more as a solution for changing the title of the course "Introduction to Web Accessibility" than for changing the title of Unit 5.
 
Regarding implementation: There is an existing resource from W3C "Implementation Plan for Web Accessibility" (https://www.w3.org/WAI/impl/resp#intro). Maybe it can be a middle solution because it is theoretical implementation planning not practical implementation.

Having said that I leave the solution to Editor's discretion.

**Comment by shawna-slh** [comment]
> There is an existing resource from W3C "Implementation Plan for Web Accessibility" (https://www.w3.org/WAI/impl/resp#intro).'

Wow - that is an old page! from 2002 -- two redesigns ago. We'll redirect all those sub-pages to the replacement resource [Planning and Managing Web Accessibility](https://www.w3.org/WAI/planning-and-managing/)

**Comment by shawna-slh** [comment]
+1 for looking at the big picture structure

I just took a look back at the [overall plan](https://www.w3.org/WAI/EO/wiki/WAI_Curricula#Draft_Outline).

To me, the sections under Developer,  Designer,  Author are "implementing".

**Comment by nitedog** [comment]
To me "implementing" also has a notion of designer/develop action, rather than the overall process. I like "Getting Started". Also "Applying" because it does not repeat "Planning" or "Managing" which are used in topic titles within the unit.

**Comment by daniel-montalvo** [comment]
Discussed (and hopefully agreed) in [This EOWG Call](https://www.w3.org/2019/09/06-eo-minutes.html#item02)
