### ISSUE TITLE
[Developer] [Module 7] “Reflected in the DOM”

### ISSUE THREAD

**Issue by hidde** [w3c/wai-curricula#296]
Regarding

> Explain how content that is dynamically generated, for example through JavaScript, needs to be properly reflected in the DOM.

Not sure what this means, can there be content that it not in the DOM? If we mean that, maybe make explicit how (canvas?)

**Comment by nitedog** [comment]
The phrase "properly reflected" was supposed to be shorthand for "provided in the corrsponding semantics and order" -- both these aspects, semantics and order, are expanded in the bullets below. Any suggestions how we can make this clearer?

**Comment by hidde** [comment]
Maybe 

> Explain how content that is dynamically generated, for example through JavaScript, should have appropriate semantics and source order.

**Comment by daniel-montalvo** [comment]
Thanks @hidde 

What is the issue exactly here if we mention "DOM"? I see the point in adding references to "appropriate semantics" and "sequential order", but I don't fully understand why we would want to change "DOM" to "source", given that we are on a Web context.
What about:

> Explain how content that is dynamically generated, for example through JavaScript, needs to have appropriate semantics and sequential DOM order.

And then, as @nitedog was suggesting, we will expand these two ideas in the learning outcomes just below.

**Comment by hidde** [comment]
I think the additions of “sequential” and “appropriate semantics” nicely clarify it. Your last suggestion sounds good to me!

**Comment by nitedog** [comment]
I feel these additions just make the sentence longer and too difficult to understand. Actually, I think "sequential order" is inacurate too -- WCAG requires "meaningful sequence".

@hidde asks:

> can there be content that it not in the DOM

No but there can be content that is not "**properly reflected** in the DOM". This is shorthand for saying "appropriate semantics" and "meaningful sequence".

**Comment by daniel-montalvo** [comment]
Will leave as it was before, then.
efe112ab83bfe2ffe8e02805e03644a7e259233a

**Comment by hidde** [comment]
I did not personally grasp this shorthand, but if we feel others will that's fine for me.

**Comment by nitedog** [comment]
Alternatively, here could be a rewrite if needed:

`Explain how content that is dynamically generated, for example through JavaScript, needs to be reflected in the DOM with appropriate semantics and meaningful order.`

I'm just hesitant we may be missing other things, like "appropriate event handlers" for example. These may also be relevant to ensure accessibility of dynamically generated code, for example for keyboard control. Happy to go either way but prefer to "appropriately reflected in the DOM" rather than trying to unpack all the details in this intro sentence -- these details are laid out in learning outcomes below.
