### ISSUE TITLE
[ED-low] Overview page - 'teaching modules' terminology

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#336]
The first sentence of the summary reads

> This resource provides teaching modules to help you create courses on digital accessibility, or to include accessibility in other courses.

I was wandering what is the most common terminology for 'teaching modules' and it seems to be 'learning modules'. Another alternative in common use is 'educational modules'. 'Learning modules' aligns better with 'learning outcomes' which is extensively used throughout the curricula.

Anyway, I don't have a strong opinion on this, so I'm happy to keep 'teaching modules'.

**Comment by nitedog** [comment]
Aren't "learning modules", "training modules", and such usually understood to be parts of actual courses rather than parts of curricula?

**Comment by daniel-montalvo** [comment]
I would keep "teaching modules" as is.

While I see the point in aligning with learning outcomes, I also see a potential danger if we change. People coming to this overview page may understand "learning modules" as if these were the modules they would need to pick to learn accessibility. And I do not think we want to say that.

Closing, since you said it was not a strong concern @carlosapaduarte . 

Feel free to reopen if needed.
