### ISSUE TITLE
Curricula on Web Accessibility -> Introduction to Web Accessibility link is broken

### ISSUE THREAD

**Issue by diegonvs** [w3c/wai-curricula#341]
When navigating to Curricula on Web Accessibility -> Introduction to Web Accessibility link is unavailable.

See:
https://www.w3.org/WAI/curricula/introduction-to-web-accessibility/

**Comment by daniel-montalvo** [comment]
Hello @diegonvs

Thanks for reaching out.

This is because we changed the name for these modules. They are now called "Foundation Modules" and you can find them at
https://www.w3.org/WAI/curricula/foundation-modules/

We think this new name better describes what these modules are about and better contextualizes this set of modules with respect to the rest of the curricula that we are developing.

I will try to set up a redirect from these old pages so that we can avoid this issue.

**Comment by diegonvs** [comment]
Great! Thanks for the quick answer @daniel-montalvo ! :)

**Comment by daniel-montalvo** [comment]
Closing, as these issues have now been solved.
