### ISSUE TITLE
[Designer Module 5: Multimedia and Animations] Topic: Movement and Animations, introduction is not self-contained

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#364]
The introductory paragraph mentions contents "below". No other topic has this kind of structure, and I would prefer this one to be self-contained also.

**Comment by daniel-montalvo** [comment]
My understanding is that the most important aspects discussed in this topic are:

- ability for content to be paused, stopped, or hidden
- use flashing that is below the general flash and red flash ratios

I have rephrased this intro so that it can be understood without looking at the learning outcomes below.
https://github.com/w3c/wai-curricula/pull/389/commits/cc75816ddeeab4135297bab4317a3206064860f6
https://deploy-preview-389--wai-curricula.netlify.app/curricula/designer-modules/multimedia-and-animations
