### ISSUE TITLE
[Designer Module 1: Flexible Layout and Design] Mixing landmarks and cues

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-curricula#372]
This seems to mix up three elements:

* Structural elements - landmarks
* Visual language - iconography and visual affordances
* Interactions design - focus

I am not sure how these fit together. Landmarks sticks out a bit as I don't see how this relates to cues.

**Comment by daniel-montalvo** [comment]
Hey @iadawn,

Thanks for this.

We saw these three closely related, as they are in a way cues for users, in addition to structural elements of the page.

- Visual landmarkss can be a cue for people to identify the different page regions
- Non-visual landmarks help identify the different regions and also help navigate through such regions quickly
- Focus indicators enable people to know where they are in the page

We saw this topic as a kind of starting point so that these concepts get mentioned in courses for visual designers, who may not get into the further and more complex modules.

Agree with you in #379 that we should expand on landmark concepts in module "Information Design" but we feel we need to at least point some of the landmark and structure concepts in the first module.

Which types of references would you be comfortable having in this first module?

**Comment by daniel-montalvo** [comment]
Closing. Implementing decision from [EOWG 8 October meeting discussion](https://www.w3.org/2021/10/08-eo-minutes#item02)
