### ISSUE TITLE
[Designer Modules] Not speaking to designers

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-curricula#384]
As I look at the list of modules I am concerned that it isn't framed around designer activities. The information is there, just in strange places.

If I were teaching designers I would probably go with a structure more like:

* Colour
* Images
* Text
* Structure and flexibility
* Forms
* Multimedia and animation

Not saying these are the right terms or are comprehensive enough but I would try to hang the content around design rather than trying to talk about design framed on WCAG.

**Comment by shawna-slh** [comment]
Would be useful to look at some web design (not coding) courses and see how the topics are arranged.

update: here is [list of design courses](https://github.com/w3c/wai-curricula/wiki/Courses-On-Web-Design) from Daniel!

**Comment by shawna-slh** [comment]
[comment moved to https://github.com/w3c/wai-curricula/issues/370 ]

**Comment by bakkenb** [comment]
@iadawn, Just a question for my clarification here...
As I read into your comment I am assuming that you believe that all the needed designer content is in the current drafted modules, the issue that you are raising is that the content does not seem to be presented in the most logical order for a designer. Checking to see how accurate that is as it will impact the amount of rework.

My question(s)... Are you recommending more of a shuffle of existing draft content to be laid out in a different order (structure) so that it is more relevant for how designers should be taught? Or does there need to be additional content written (added), or large scale edits to reorganize and rewrite bits and pieces of the content to get it aligned with the structure that you propose?

**Comment by iadawn** [comment]
Broadly speaking, yes. The content is there, I just don't think it is organised in a way that makes it digestible to a design professional. I also don't think it really speaks their 'language'.

**Comment by bakkenb** [comment]
I think it might be helpful to put the existing draft structure and the proposed structure in front of a few "working" UI and Visual Designers outside of EOWG and ask if there are issues with the current structure, or if they would prefer the proposed structure, and why.

**Comment by iadawn** [comment]
Agreed... I will see if I can find a couple of tame folks around here to test it out on.

**Comment by daniel-montalvo** [comment]
Hey @iadawn 

Thanks for your input on this. Let me give you a bit of background about why we chose to use this structure in the TF, that we presented in the [Eagle Review](https://www.w3.org/2002/09/wbs/35532/curriculaDesignerModulesEagleReview/results) survey back in March.

- We wanted to address of course visual designers, but also UI designers, and interaction designers, some of which may work closely together with developers. For context see [TF minutes February 9](https://www.w3.org/2021/02/09-wai-curricula-minutes.html).
- We researched [several courses on Web design](https://github.com/w3c/wai-curricula/wiki/Courses-On-Web-Design). What we found out is that most of these courses addressed both visual, UI, interaction designers, as well as some developer concepts at the same time. That gave us the impression that, while we should consider the differences between designers and developers, we needed also to tie these two curricula parts together so that it is easier for instructors to use the two parts in combination if need be.

I think the structure you are proposing would work well for visual designers, but those mixed profiles we talked about above would probably miss the interaction aspects and the ties to developer concepts we have included in this structure.

What are your thoughts on this?

**Comment by daniel-montalvo** [comment]
We discussed this in [today's EOWG call](https://www.w3.org/2021/07/30-eo-minutes#item03).

The proposal is

- We definitely acknowledge that this issue needs to be addressed, and will work together with you and other commenters who also pointed out the structural and language issues to resolve them
- We would however start with the most specific issues as we think these will lead us to some further and more significant language and structural changes.
- In the meantime, we will put a sentence in the [designer Modules Overview Page](https://wai-curricula.netlify.app/curricula/designer-modules/) along the lines of:
  "These modules have been organized so that they can be easily taught together with the developer modules. If you are teaching other audiences, feel free to change the structure/language so that it fits your audience needs".
  And will reexamine at the end of the process if the sentence is worth keeping or we all have agreed on a better structure/language.

**Comment by daniel-montalvo** [comment]
<p>Please take a look at:</p>
<ul>
  <li><a href="https://github.com/w3c/wai-curricula/pull/389/files#diff-ec1ccf6414e02b12ba2d4f77b185b85bfcacae7839332b6a77b954c928d44326">Designer Modules Overall Structure Diff</a>
  <li><a href="https://deploy-preview-389--wai-curricula.netlify.app/curricula/designer-modules/">Designer Modules Live Draft</a></li>
</li>
<p>Main changes include</p>
<ul>
  <li>Module 1: "Flexible Layout and Design" -> "Color and Layout" + topic restructuring</li>
  <li>Module 2 "Information Design" was previously Module 3.</li>
  <li>Module 3 "Navigation" was previously module 2</li>
  <li>Module 6 "Interactions and Feedback" -> "Forms, Interactions, and Feedback" + topic restructuring</li>
  
</ul>
<p>Would you be comfortable with this new structure based on <a href="https://github.com/w3c/wai-curricula/issues/384#issuecomment-888421267">my comment above?</a></p>

**Comment by iadawn** [comment]
> * "These modules have been organized so that they can be easily taught together with the developer modules. If you are teaching other audiences, feel free to change the structure/language so that it fits your audience needs".

Not sure about this one. I don't know how likely it is that teaching of designers would overlap with that of teaching developers. Not sure what problem this is trying to solve.

**Comment by iadawn** [comment]
https://github.com/w3c/wai-curricula/issues/384#issuecomment-905327980

More comfortable :) I still think there are a few things that lean towards a particular structure simply because that is how other resources are structure rather than it needing to be that way. But this is minor really.

**Comment by daniel-montalvo** [comment]
Closing, as I think we all have agreed on overall structure.

I will be getting to the other minor things you mention, as I think they are spread through the remaining open issues.
