### ISSUE TITLE
[overall] module numbering

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-curricula#385]
From @MicheleAWilliams-A11y in [survey](https://www.w3.org/2002/09/wbs/35532/curricula-designers-starfish/results)
> Just a clarification question - will all the modules have the same numbers? It's a bit confusing and jarring that the prerequisite modules are titled the same (e.g., in "Module 2: Navigation" it references prerequisite "Module 6: Understanding and Involving Users"). It's making things hard to track.

See for example [developer module first page](https://www.w3.org/WAI/curricula/developer-modules/)

+1 that this is an issue.

Off-top-of-head idea to address it:
* add letter before number, e.g.,
> Module F1: What is Web accessibility (Foundations)
> Module D1: Page Structure  (Developer)
> Module U1: ... (UI Designer and other designers)
> Module W1: ... (Writer)

**Comment by daniel-montalvo** [comment]
Hey @shawna-slh @MicheleAWilliams-A11y

I am leaning towards

* "Foundation Module x",
* "Developer Module x"
* "Designer Module x"
* "Author Module x"

The complete words would be easier to understand and interpret. First letters may take a while for some to interpret unless we explained them. I also find these letters a bit awkward. Why writers instead of authors? Why UI designers instead of Visual Designers?

I also think we should qualify only when we are referencing the modules from other parts, such as when we are referring to the developer modules from the designer part, or viceversa. The page titles should remain as they are now, as readers can infer which part they are in from the left nav and from the breadcrumb section.

Thoughts?

**Comment by shawna-slh** [comment]
Maybe there is an even simpler way to increase clarity, limit confusion, and avoid clutter?

Idea 2: Put module group in headings. For example, on [Developer fist page](https://www.w3.org/WAI/curricula/developer-modules/)
* h2 "Modules" change to: "Developer Modules"
* h2 "Prerequisites for Students" change to something like:
   * "Prerequisites for Students from Foundation Modules"
   * "Prerequisites from Foundation Modules" or "Foundation Module Prerequisites"<br>(and put "students" in the intro sentence)
   * "Foundation Module Student Prerequisites"

Ideas 3: Eliminate numbers all together. The modules all have fairly short titles/names, and they are never listed with just number (without title/name). What is the benefit of using numbers? (I thought of that before, but didn't think it was worthy of comment.)

<hr>

I haven't looked carefully to have a strong opinion on any option. :-) I'm happy going with editor preference with TF consensus.

@daniel-montalvo If easy, you might want to mock up options so people can actually see they impact of implementing them. (For example, I think adding "Foundations" before each module # is unnecessary clutter, yet maybe others would find it helpful?)

**Comment by daniel-montalvo** [comment]
Thanks for these suggestions, @shawna-slh 

I have implemented heading level 2 name changes at

- [Designer Modules Overview Page](https://deploy-preview-389--wai-curricula.netlify.app/curricula/designer-modules) (number at start)
- [Developer Modules Overview Page](https://deploy-preview-389--wai-curricula.netlify.app/curricula/developer-modules) (no number at start)
To see what people think about these two proposals.

There is another scenario where the entire word at the beginning could work. see
https://wai-curricula.netlify.app/curricula/designer-modules/navigation/#topic-location

There we ask instructors to build on a foundation module. We say:

> Build on foundation [Module 6: Understanding and Involving Users](/curricula/foundation-modules/understanding-and-involving-users/) to research strategies that people with disabilities use to locate a specific web page in a set of web pages. Discuss examples like breadcrumb trails, page titles, and visual cues to indicate the current page.

In
https://deploy-preview-389--wai-curricula.netlify.app/curricula/designer-modules/navigation/#topic-location
I have made the word "Foundation" part of the link, so that it is clear that we are referring to the foundation modules. Happy to discuss if we should remove numbering from these instances.

**Comment by shawna-slh** [comment]
> I have implemented heading level 2 name changes at
>- [Designer Modules Overview Page](https://wai-curricula.netlify.app/curricula/designer-modules) (number at start)
> - [Developer Modules Overview Page](https://wai-curricula.netlify.app/curricula/developer-modules) (no number at start)

I'm not seeing the number change or heading change.

> I have made the word "Foundation" part of the link, so that it is clear that we are referring to the foundation modules.

+1

> Happy to discuss if we should remove numbering from these instances.

I'll leave that to you, @MicheleAWilliams-A11y , and the Task Force. :-)

**Comment by daniel-montalvo** [comment]
> > I have implemented heading level 2 name changes at
> > 
> > * [Designer Modules Overview Page](https://deploy-preview-389--wai-curricula.netlify.app/curricula/designer-modules) (number at start)
> > * [Developer Modules Overview Page](https://deploy-preview-389--wai-curricula.netlify.app/curricula/developer-modules) (no number at start)
> 
> I'm not seeing the number change or heading change.

The above should be pointing to the live draft, my mistake that I pointed to the previous iteration.

> > I have made the word "Foundation" part of the link, so that it is clear that we are referring to the foundation modules.
> 
> +1
> 
> > Happy to discuss if we should remove numbering from these instances.
> 
> I'll leave that to you, @MicheleAWilliams-A11y , and the Task Force. :-)

> Off-top-of-head idea to address it:

> add letter before number,

The TF has been discussing this [3 August](https://www.w3.org/2021/08/03-wai-curricula-minutes.html#item06).

First letter only is confusing. There seemed to be agreement on  distinctive names in cross references, page title, and URL

We would have something like:

* FOU 1: What is Web accessibility (Foundations)
* DEV 1: Page Structure (Developer)
* DES 1: ... (UI Designer and other designers)
* CP 1: ... (Writer)

**Comment by MicheleAWilliams-A11y** [comment]
I don't know all the examples but the one that said include "Foundation" as part of the link as in "Foundation Module 6" makes a lot of sense. That then matches how it's referenced in prior pages from what I can see (but I've only seen the Designer and Foundation ones listed as part of this survey review).
