### ISSUE TITLE
[Designer Module 5: Multimedia and Animations] Unclear scope

### ISSUE THREAD

**Issue by daniel-montalvo** [w3c/wai-curricula#388]
From @shawna-slh  in
https://www.w3.org/2002/09/wbs/35532/curricula-designers-starfish/results#xq14

I am unclear the scope and goals of this module. My first reactions were:

* This should be more like our resource Making Audio and Video Media Accessible (https://www.w3.org/WAI/media/av/)
* This shouldn’t have much about designing media players because that is a very rare task (in most situations, it’s best to use an existing player designed
for accessibility)

Then, humm – I wonder what should be in designing modules versus writing modules?

Depending on the answers to above, I would have different comments on this module -- fairly significant comments.
To help instructors (and other reviewers :-), I think it warrants a note early in the page briefly mentioning scope and relationship with writing modules
– that is, what is covered here and what is covered there.

---

### Terminology decided for WAI media resource

Different areas use “audio description”, “video description”, “described video”, and other terminology. We debated terminology in light of user research
that highlighted that “audio description” is totally misunderstood by many, whereas “video description” makes sense -- along with the fact that description
does not need to be audio (can be provided as text file in some cases). Therefore, we decided to use “description of visual information” on first uses
(along with “Description of visual information is called audio description, video description, or described video in different areas.”).
And then throughout the resource use just “description”. I hope it works to use the same terminology in the curricula.

-------

### Teaching Resources

https://www.w3.org/WAI/media/av/users-orgs/
 covers media specifically and links to “Video Captions (Web Accessibility Perspectives)” and “How People with Disabilities Use the Web” – so maybe replace
the two links with the one?

**Comment by daniel-montalvo** [comment]
Hey @shawna-slh 

> * This should be more like our resource Making Audio and Video Media Accessible (https://www.w3.org/WAI/media/av/)

+1, will work on making this module closer to media guide.

> * This shouldn’t have much about designing media players because that is a very rare task (in most situations, it’s best to use an existing player designed for accessibility)

We discussed to which extent we should talk about designing media players in [TF meeting June 1](https://www.w3.org/2021/06/01-wai-curricula-minutes.html#t03).

There seemed to be agreement that we should at least provide some guidance. Agree with you that we should also mention that it is always better to pick up an accessible media player than trying to design one on your own, but that is what some orgs are going to do anyway.

> Then, humm – I wonder what should be in designing modules versus writing modules?

- Designers: appearance of multimedia content, how it shows up on the page, how alternatives are presented, how alternatives are turned on or off, avoid overlaps etc
- Author: specifics on how to provide the content, how to write audio descriptions, integrated descriptions, captions, etc.

> Depending on the answers to above, I would have different comments on this module -- fairly significant comments.
> To help instructors (and other reviewers :-), I think it warrants a note early in the page briefly mentioning scope and relationship with writing modules
> – that is, what is covered here and what is covered there.

**Comment by daniel-montalvo** [comment]
<p>I have been working on this. Main changes include:</p> 
<ul>
  <li>moving away from WCAG terminology and using the more up-to-date terms in the resource <a href="https://www.w3.org/WAI/media/av/">Making Audio and Video Media Accessible</a></li>
  <li>Include advice that it is better to use an existing media player with support for accessibility than to develop and ad hoc media player from scratch. Something along the lines of "assess the need for designing custom media players versus using existing media players with support for accessibility"</li>
  <LI>Broaden scope of second topic "Animations" and explicitly include carousel requirements</li>  
</ul>
<p>For a detailed review of the changes, please see the <a href="https://github.com/w3c/wai-curricula/pull/389/files#diff-dea03a282537c914e0f99542a9491d92c938fed22078f790ae4a736d5ca8e132">Multimedia and Animations module diff</a> and the <a href="https://deploy-preview-389--wai-curricula.netlify.app/curricula/designer-modules/multimedia-and-animations/">Preview for Multimedia and Animations</a>.</p>
<ul>
  <li>Do you think these changes make this module more consistent with the resource?</li>
  <li>Do you think strongly that we should not cover media player design at all in this module</li>

**Comment by shawna-slh** [comment]
Can you give me the link to preview for this?

**Comment by daniel-montalvo** [comment]
https://deploy-preview-389--wai-curricula.netlify.app/curricula/designer-modules/multimedia-and-animations/

**Comment by shawna-slh** [comment]
Hi @daniel-montalvo
Thanks for working on the issues I noted. And thanks for your patience with me handling other projects before getting to this.

### Summary
I support covering media player accessibility. I like the approach of understanding player issues and ensuring player accessibility, rather than the approach of designing one yourself. I think this draft is going in a good direction, and will be the right approach once it is polished.

### Overall Focus/Approach

From the [TF minutes 1 June](https://github.com/w3c/wai-curricula/issues/388), it looks like the agreement was to include that providing an accessible media player is joint responsibility of designer and developer. +1 from me
I’m not clear from the minutes how much detail the TF wanted to go into on designing a custom media player.

I think the challenge with covering the media player specifics is not letting it overshadow the other things. Again, since few people will design a custom media player, and everyone will need to know how to handle media alternatives. I do support mentioning media player accessibility, for sure.

I think the coverage of media players is inconsistent in this draft. In the overall “Learning Outcomes for Module”, it seems the media player has too much detail (part of that was my mistake from quick skim – more on that below). Whereas, “Teaching Ideas for Topic” feels like to me it has the right about of coverage in relationship to the other aspects. So maybe tweakinf the “Learning Outcomes for Module” will help a lot?

I like the general idea of focusing on: “evaluate the need for designing custom media players and select existing media players with support for accessibility where possible”. (Maybe also mention that one is open source, so even if you decide to customize, you could start with that.)

So overall, I think this is probably a very good approach – it just needs to be polished. *And* I appreciate that you waited to polish until after getting agreement on the overall approach. That is wise. :)

<hr>

### Wording Tweaks

Since we’re saying usually they will use an existing media player, and not create a custom one, how about change:
> design media player(s)…

to:
> ensure media player(s)…

and change:
> design player controls

to:
> ensure player controls…

<hr>

### Learning Outcomes for Module

User flow and thoughts from informal usability testing report on draft of 17 Sept:
* … skims… Learning Outcomes … “geesh, that’s a long list. too hard to process. needs to be categorized”
* … skims, “fourth bullet addresses media players … looks like the rest of them do, too – well, I’m not going to cover that, so I can skip the rest of these.
* this has too much emphasis on what to do for media players (which few people will do) and not enough on what *everyone* will have to do for multimedia

… [later]
* I thought the 2 bullets “design mechanisms to mute and control the volume…” and “design mechanisms to pause, stop…” were for the media player! and then I guessed the others were, too. Now that I read more carefully (and because I understand the content), I see they are different.

If you stick with this general content, I suggested grouping the items. Below is just a rough draft concept – you’d need to do the wording better.

* identify accessibility requirements for different types of audio and video content
* design user experiences for description, captions, transcripts, and sign languages, including:
  * placement and spacing for alternatives to multimedia content 
  * mechanisms for turning on and off alternatives
  * ways for users to interact with the alternatives
* understand media player issues:
  * evaluate the need for designing custom media players and select existing media players with support for accessibility where possible
  * design media players with support for different methods of interaction, including mouse, keyboard, touch, and voice
  * design media player controls that have clear and descriptive names, that are easy to find, and that are always reachable for users **[actually, I think you don’t need this detail at the “Learning Outcomes for Module” level]**
* design mechanisms to control automatic audio or movement:
  * to mute and control the volume of auto-playing audio
  * to pause, stop, and hide moving, blinking, and auto-updating content, including animations and carousels
* identify related requirements for:
  * developers to programmatically associate alternatives and descriptions to their corresponding media content
  * developers to include accessibility support for media players
  * content authors to provide appropriate text transcripts, captions, audio descriptions, and sign language

<hr>

### Little bug in learning outcomes for Topic: Alternatives to Multimedia Content

I see that “Topic: Alternatives to Multimedia Content”, “Learning Outcomes for Topic” includes:
> * design mechanisms for controlling the volume of audio that plays automatically for more than 3 seconds
> * design mechanisms to pause, stop, or hide alternatives to multimedia content that blink, move, or auto-update

However, I think those are covered in the next topic,  “Topic: Movement and Animations”.

**Comment by shawna-slh** [comment]
### Description terminology

See the [issue to further edit the Media resource to limit “audio description”]( https://github.com/w3c/wai-media-guide/issues/182).

I look forward to more input on that terminology in the Media resource and in the Curricula.

The proposal is:
1. on first use (and maybe first use in multiple sections), use:
> “description of visual information, which is also referred to as audio description, video description, or described video

2. in subsequent uses, use
> description of visual information

or just:
> description

To have that discussion in one place, I suggest folks comment on that in the [Media resource issue]( https://github.com/w3c/wai-media-guide/issues/182) rather than here.

**Comment by daniel-montalvo** [comment]
Closing this as I think these concerns have now been addressed.
- Implemented decisions in [EOWG 8 October](https://www.w3.org/2021/10/08-eo-minutes#item04)
- https://wai-curricula.netlify.app/curricula/designer-modules/multimedia-and-animations/
