### ISSUE TITLE
[Designer Module 1: Visual Design] Adding something about text alignment to Topic: Styles

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#401]
Should we include text alignment in this topic? We address spacing but not alignment but this is also relevant (G169).

**Comment by daniel-montalvo** [comment]
Hey @carlosapaduarte 

I added this in https://github.com/w3c/wai-curricula/commit/c8795b5aa3a05b2b72e7045748a2e6378dae9dff

For preview, see
https://deploy-preview-433--wai-curricula.netlify.app/curricula/designer-modules/visual-design/#topic-styles

I would appreciate your input on the phrase "Explain that it is difficult for some users to read justified text due to the unpredictable spacing created by the justification". Is this a good way to explain the problem? The technique is not very specific on what the problem is. They refer to "rivers of white running down the page", which IMO is not very easy to understand.

**Comment by carlosapaduarte** [comment]
I propose a small edit, replacing unpredictable with uneven. We could have a longer version explaining that because of the uneven spacing, we can get those rivers of whitespace running down the page, but I don't think we need to go to that level of detail here. 

> Show examples of text aligned to the left, to the right, and justified. Explain that it is difficult for some users to read justified text due to the uneven spaces between letters and words created by the justification. Therefore, text should align to only one side where possible to enhance readability. For reference, see technique [G169: Aligning Text on Only One Side](https://www.w3.org/WAI/WCAG21/Techniques/general/G169).

**Comment by daniel-montalvo** [comment]
That's done now in 94511bc6557f2a1b9f5dc6e62b23351657106387.
