### ISSUE TITLE
[Designer Module 2: Information Design] "names for components" in Topic: Naming and Grouping

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#403]
We use "names for components" multiple times in this topic (and elsewhere in the module). I am not sure if a component's name is a clear concept to a designer. I am also not sure that this an issue that needs to be tackled, because these resources target trainers not trainees (the designers). But I decided to raise it to gauge the opinion of others.

**Comment by daniel-montalvo** [comment]
Yes, let's see what others think, @carlosapaduarte 

Just for background, when we started building this module we had "labels" instead of "names for components" and that was flagged as too difficult a concept for both designers and instructors.

**Comment by carlosapaduarte** [comment]
I seem to remember the discussion around labels and that it might be confused with the labels of form elements. Or maybe I'm making this up in my head :-)

**Comment by daniel-montalvo** [comment]
No, you are not. That is yet another reason why we stopped using labels here. Happy to explore other phrases different than "names for components"

**Comment by daniel-montalvo** [comment]
Preview with changes at
https://deploy-preview-433--wai-curricula.netlify.app/curricula/designer-modules/information-design/#topic-naming-and-grouping

* Back to using "labels" instead of "names for components".
* Explained that some labels are actually names to supplement information conveyed through graphics and other images, for example in links, buttons, and form elements

**Comment by daniel-montalvo** [comment]
Agreed in https://www.w3.org/2021/12/07-wai-curricula-minutes.html#item06
