### ISSUE TITLE
[Designer Module 5: Images and Graphics] Suggestion of an idea to assess knowledge for topic Informative Images

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#413]
There is no idea to assess knowledge in this topic related to the image descriptions. I offer this suggestion:

Practical - Give students a collection of related images and ask them to craft boilerplate descriptions that could be used to provide descriptions for that collection. Asses how students identify requirements in the boilerplate descriptions that support appropriate image descriptions.

**Comment by daniel-montalvo** [comment]
That's good point. That was missing, thanks for bringing this up.

Building on your suggestion, I have come up with:

> Practical &mdash; Give students a set of informative images. Ask students to annotate text alternatives that help developers and content authors provide the descriptions in the implementation phase. Assess how students provide boilerplate descriptions that would then be completed and maintained through the development and authoring phases.

But I am not really sure if the ask here, being able to annotate these possible descriptions so that other roles have guidance on what they need to provide later on in the implementation phase, is sufficiently conveyed. This may be a good discussion for the TF meeting next Tuesday.

**Comment by daniel-montalvo** [comment]
Added in https://github.com/w3c/wai-curricula/commit/8649955671f2963c199eb028abade8a07d61bb80

See preview at
https://deploy-preview-433--wai-curricula.netlify.app/curricula/designer-modules/images-and-graphics/#topic-informative-images
