### ISSUE TITLE
[Designer Module 6: Multimedia and Animations] Question about sign language in the teaching ideas for topic Alternatives to Multimedia Content

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#419]
When addressing sign languages I wonder if we should mention that there is not just a single sign language but that there are multiple sign languages (like spoken and written languages), so the designer considers this in the design (e.g., the design might need to provide a selection mechanism)?

**Comment by daniel-montalvo** [comment]
Thanks for raising this @carlosapaduarte 

There are currently two instances in this topic where we use "sign language" (singular).
* Learning outcomes, second bullet
* Teaching ideas, fourth bullet

Will change these to plural and also tweak the teaching idea so that it reflects your comment better.

**Comment by daniel-montalvo** [comment]
I took a pass based on comments. For preview, see
https://deploy-preview-433--wai-curricula.netlify.app/curricula/designer-modules/multimedia-na-d-animations/#topic-alternatives-to-multimedia-content

* Teaching Ideas, fourth bullet
  * Added the diversity of sign languages depending on region and country.
  * Changed "understand written language well" to "use written language as their second language" to avoid judgement.
  * Clarified that some deaf people do not use sign language.
