### ISSUE TITLE
[Module 6: Labels and Instructions] Do we need this as a module?

### ISSUE THREAD

**Issue by carlosapaduarte** [w3c/wai-curricula#478]
While I agree the content in this module is required, while reading the learning outcomes it felt like a subset of Module 1: Content Clarity
What are the disadvantages of moving this content to the first module? Would it become too large?

**Comment by bakkenb** [comment]
I was wondering the same thing. If Module 1 was "Understandable Content," then most of this would fit nicely in that module as well.

**Comment by eoncins** [comment]
Agree with the comments, as the first module is on difficult language/words and module 6 would be a specific application (labels and instructions). As Carlos, I also wonder if then it might become too large.

**Comment by daniel-montalvo** [comment]
Hi @carlosapaduarte @eoncins @bakkenb 

Agree with you all's assessment. I am proposing this as a separate module because:

* "Labels and Instructions" focuses more in the context of forms and controls, whereas module 1 focuses on content overall
* Including these contents in the first module could create an extra long module 1 and we may be mindful of the balance between modules.

We could put it forward in the sequence, closer to the first module. We could also merge this into the first module, which I am hesitant about.

Let's discuss in our TF meeting on Tuesday.

**Comment by daniel-montalvo** [comment]
Discussed in [15 March meeting](https://www.w3.org/2022/03/15-wai-curricula-minutes.html#item02)

We will

* keep as a module.
* change title to "Forms" for now 
* revisit order later.
