### ISSUE TITLE
[Content Author Module1] Teaching ideas

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-curricula#515]
When we advise clear language we have a special responsibility to write clearly and crisply ourselves. The language in this section could be sharper, more direct, and model the mode we are recommending. Something like:

* Give students text comparisons.  Provide text passages with clear language that is easy to read and understand. Compare those with passages that are overly complex and harder to understand. Emphasize that clear writing is essential for people with disabilities to effectively use content. Note that there is benefit to this for all users.
* Compare active versus passive voice in sentence structures. Explain how understanding is improved by using direct language and clear identification of the source of the action. Connect this technique to the ability of several groups of people with disabilities to understand content.
* Demonstrate how different font types and sizes impact readability. Demonstrate use of font types, such as Sans Serif, that provide a good reading experience. Providing the text is a content author’s responsibility. Defining which fonts to use is a designer’s responsibility.

**Comment by daniel-montalvo** [comment]
Many thanks for bringing this to my attention, @sharronrush 

This is now updated in teaching ideas for topic "Easy to Understand Language".
https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/clear-content/#topic-easy-to-understand-language

This section has changed significantly since the last review.

I am closing this as I think it looks overall much clearer, feel free to open new issues if you have further suggestions for the thorough review period.

**Comment by daniel-montalvo** [comment]
Many thanks for bringing this to my attention, @sharronrush 

This is now updated in teaching ideas for topic "Easy to Understand Language".
https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/clear-content/#topic-easy-to-understand-language

This section has changed significantly since the last review.

I am closing this as I think it looks overall much clearer, feel free to open new issues if you have further suggestions for the thorough review period.
