### ISSUE TITLE
[all] include "Curricula" in title

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-curricula#541]
currently it's:
> Module 0: Title of Module | Web Accessibility Initiative (WAI) | W3C

UPDATE BELOW

<s>
At minimum, I think we should add "Curricula":
> Module 0: Title of Module | Curricula | Web Accessibility Initiative (WAI) | W3C

Maybe also category. Maybe just "WAI":
> Module 0: Title of Module | Developers | Curricula | WAI | W3C
</s>

**Comment by daniel-montalvo** [comment]
Thanks @shawna-slh 
We have been postponing this until the very end of the cycle when we have the whole picture and I think it makes perfect sense.

I would do:

- "Foundation Module 0: Module Title | Curricula | W3C/WAI"
- "Developer Module 0: Module Title | Curricula | W3C/WAI"
- "Designer Module 0: Module Title | Curricula | W3C/WAI"
- "Content Author Module 0: Module Title | Curricula | W3C/WAI"

I could just try to put these as strings in the "title" key, but I wonder if we could do this more elegantly using other keys that I may not be familiar with.

Maybe @SteveALee  has some input here...

**Comment by shawna-slh** [comment]
@daniel-montalvo Currently, WAI site titles are similar to a reverse breadcrumb and end in
> ... | Web Accessibility Initiative (WAI) | W3C

or

> ... | WAI | W3C

I assume we want to stick with that. (not "W3C/WAI")

Per our discussion in EO-Plan today, maybe we want to frontload the module name for frequent users of a set of modules? And let people who land on a page from a search engine get the context from the h1 and breadcrumb, rather than all from the title?

Note that visually, many people see only the first word or two or three of the title in a browser tab -- depending on their configuration. (At least I usually see only one or two words. Maybe others see more?) Therefore, the first words are important when one has multiple tabs open.

Thinking more on that, because all of the info is in *both* the h1 and the breadcrumb, what about making the title even more succinct, and leaving out "Module 0:"? For example, two with same module name to show where clarification of module set is important:

<hr>

1. https://www.w3.org/WAI/curricula/developer-modules/forms/

h1:
> Module 5: Forms<br>in [Developer Modules](https://www.w3.org/WAI/curricula/developer-modules/), [Curricula on Web Accessibility](https://www.w3.org/WAI/curricula/)

breadcrumb:
> [Home](https://www.w3.org/WAI/) | [Teach & Advocate](https://www.w3.org/WAI/teach-advocate/) | [Curricula on Web Accessibility](https://www.w3.org/WAI/curricula/) | [Developer Modules](https://www.w3.org/WAI/curricula/developer-modules/) | **[Forms](https://www.w3.org/WAI/curricula/developer-modules/forms/)**

title:
>Forms | Developers | Curricula | WAI | W3C

or (I like better)
> Forms in Developer Curricula | WAI | W3C

or (only if strong reason to include "modules")
> Forms in Developer Modules | Curricula | WAI | W3C

<hr>

2. https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/forms/

h1:
> Module 3: Forms<br>in [Content Author Modules](https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/), [Curricula on Web Accessibility](https://content-author-modules--wai-curricula.netlify.app/curricula/)

breadcrumb:
>[Home](https://content-author-modules--wai-curricula.netlify.app/) | [Teach & Advocate](https://content-author-modules--wai-curricula.netlify.app/teach-advocate/) | [Curricula on Web Accessibility](https://content-author-modules--wai-curricula.netlify.app/curricula/) | [Content Author Modules](https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/) | **[Forms](https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/forms/)**

title:
>Forms | Content Authors | Curricula | WAI | W3C

or
> Forms in Content Author Curricula | WAI | W3C

or
> Forms in Content Author Modules | Curricula | WAI | W3C

**Comment by shawna-slh** [comment]
Steve helped with ```<title>``` for the recent minimal header resources, and I expect he can help with this. :-)

@SteveALee, I would say this is medium priority for you, not high.

**Comment by SteveALee** [comment]
Short story is by setting the `title` variable in each page you can get the form

  <title>{page.title} | Web Accessibility Initiative (WAI) | W3C></title>

If the variable `title_html` is not set then `title` is also used for the page H1

That is a lot of repetition for you, but abstracting and simplifying would require extra work to the dafault_layout due to the limitations of jekyll front matter.

## Details

The WAI theme confusingly used the term Title for both the HTML title element that the browser shows in window/tab title bar and also the first H1 on a page

The H1 is set by the page "title_html" front matter variable if defined else the page "title" variable

The code to set the title also uses the "title" variable and is defined in the layout. wai-curricular uses the default layout. The version Shawn mentioned is for the standalone _resouce layout and is different. They both uses a number of variables to define the HTML title element content. Plus they reverses the order of these for RTL languages

The bit you care about is defined in the default layout as:

  <title>{page.title} | Web Accessibility Initiative (WAI) | W3C></title>

The full code is here https://github.com/w3c/wai-website-theme/blob/master/_layouts/default.html#L26

So you can set the page title as you like in each page's front matter, as you suggest. The rest is fixed unless we make changes to support variations.

It is also possible to set a default page.title variable to be used if it is not set in a page. This has to be done in the _config file.

Does that answer you question?

**Comment by daniel-montalvo** [comment]
Thanks @SteveALee  for these clear and detailed explanations.

So for our specific case here:

- We can control the first part of what shows up in the title of each page via the "title" key. It supports pipes (|) and as far as I know there is no difference in style with respect to the second part of the title given @SteveALee  comments.
- The second part of what shows sup in the title "| Web Accessibility Initiative (WAI) \ W3C" we cannot change at the curricula level unless we schedule some more template work to add some more variables to this. I'll let you both @SteveALee  and @shawna-slh  to figure out how much of a priority this is based on current situation. But I would say this should not be much of a priority at this point.

**Comment by daniel-montalvo** [comment]
Thanks much @shawna-slh 

> @daniel-montalvo Currently, WAI site titles are similar to a reverse breadcrumb and end in
> 
> > ... | Web Accessibility Initiative (WAI) | W3C
> 
> or
> 
> > ... | WAI | W3C
> 
> I assume we want to stick with that. (not "W3C/WAI")

I propose to stick with the first one based on above comments and current layout development.

> Per our discussion in EO-Plan today, maybe we want to frontload the module name for frequent users of a set of modules? And let people who land on a page from a search engine get the context from the h1 and breadcrumb, rather than all from the title?
> 
> Note that visually, many people see only the first word or two or three of the title in a browser tab -- depending on their configuration. (At least I usually see only one or two words. Maybe others see more?) Therefore, the first words are important when one has multiple tabs open.
> 
> Thinking more on that, because all of the info is in _both_ the h1 and the breadcrumb, what about making the title even more succinct, and leaving out "Module 0:"? For example, two with same module name to show where clarification of module set is important:

I think numbering indicates the proposed teaching sequence and should be also in title. We could just have "1" instead of current "Module 1:" for short.

> 1. https://www.w3.org/WAI/curricula/developer-modules/forms/
> 
> h1:
> 
> > Module 5: Formsin [Developer Modules](https://www.w3.org/WAI/curricula/developer-modules/), [Curricula on Web Accessibility](https://www.w3.org/WAI/curricula/)
> 
> breadcrumb:
> 
> > [Home](https://www.w3.org/WAI/) | [Teach & Advocate](https://www.w3.org/WAI/teach-advocate/) | [Curricula on Web Accessibility](https://www.w3.org/WAI/curricula/) | [Developer Modules](https://www.w3.org/WAI/curricula/developer-modules/) | **[Forms](https://www.w3.org/WAI/curricula/developer-modules/forms/)**
> 
> title:
> 
> > Forms | Developers | Curricula | WAI | W3C
> 
> or (I like better)
> 
> > Forms in Developer Curricula | WAI | W3C
> 
> or (only if strong reason to include "modules")
> 
> > Forms in Developer Modules | Curricula | WAI | W3C
> 2. https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/forms/
> 
> h1:
> 
> > Module 3: Formsin [Content Author Modules](https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/), [Curricula on Web Accessibility](https://content-author-modules--wai-curricula.netlify.app/curricula/)
> 
> breadcrumb:
> 
> > [Home](https://content-author-modules--wai-curricula.netlify.app/) | [Teach & Advocate](https://content-author-modules--wai-curricula.netlify.app/teach-advocate/) | [Curricula on Web Accessibility](https://content-author-modules--wai-curricula.netlify.app/curricula/) | [Content Author Modules](https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/) | **[Forms](https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/forms/)**
> 
> title:
> 
> > Forms | Content Authors | Curricula | WAI | W3C
> 
> or
> 
> > Forms in Content Author Curricula | WAI | W3C
> 
> or
> 
> > Forms in Content Author Modules | Curricula | WAI | W3C

The resources are called:

- Foundation Modules
- Developer Modules
- Designer Modules
- Content Author Modules

It is weird if we say "Developers Curricula" in title and then the resource itself is called "Developer Modules". I would feel more comfortable if we say "Developer Modules" also in title.

I would go for:

> > 5: Forms in Developer Modules | Curricula | Web Accessibility Initiative (WAI) | W3C
> > 3: Forms in Content Author Modules | Curricula | Web Accessibility Initiative (WAI) | W3C

**Comment by shawna-slh** [comment]
_(I had forgotten that the numbering actually is suggestive of order. In some other resources, we say order not implied, e.g., in planning & managing: "These activities are not necessarily carried out in sequence".)_

> I would go for:
> 5: Forms in Developer Modules | Curricula | Web Accessibility Initiative (WAI) | W3C
> 3: Forms in Content Author Modules | Curricula | Web Accessibility Initiative (WAI) | W3C

I like it. Go for it!

**Comment by daniel-montalvo** [comment]
Great to hear.

Will leave it open so people have the chance to see these in context as it affects the other parts.

Content author modules are now updated, others are pending.

**Comment by daniel-montalvo** [comment]
Closing, this is already addressed.
