### ISSUE TITLE
[Content Author Module 3: Forms] Teaching example for Instructions unclear

### ISSUE THREAD

**Issue by MicheleAWilliams-A11y** [w3c/wai-curricula#547]
The following Teaching Idea for instructions is unclear to me and seems redundant to the rest of the examples. Overall it seems to just restate the topics of the section which isn't very meaningful. I wouldn't know what kind of example to create. I recommend simply removing it.

>Demonstrate assistive technology interaction with form fields and controls that have meaningful instructions. Then demonstrate interaction with form fields and controls that do not have such instructions. Reflect with students on how these instructions help all users, including those with disabilities, to provide the appropriate input and to understand the form purpose.

**Comment by daniel-montalvo** [comment]
Thanks @MicheleAWilliams-A11y

I particularly see value in having these separate teaching ideas, each focusing on specific strategies to get to labels, instructions, and error messages. I am assuming that these differences were not very clear and that's why you thought they were pretty much the same. Due to the structure of the curricula with no "teaching ideas for module" that can apply to all topics, we need to repeat some of them per topic and make an extra effort to clarify the specifics clear.

I have taken a pass at these at:
https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/forms/

Topic Labels

> Demonstrate the use of voice commands, keystrokes, and gestures for assistive technologies to get to the label associated with a form field or control. Explain that several groups of users require labels that clearly describe the purpose of the controls. Show how successful form interaction becomes difficult or impossible without such labels.

Topic Instructions

> Demonstrate the use of voice commands, keystrokes, and gestures for assistive technologies to get to the instructions associated with form fields and controls. Explain that several groups of users require meaningful instructions to provide the appropriate input. Show how successful form interaction becomes difficult or impossible without such instructions.

Topic Error Messages

Demonstrate the use of voice commands, keystrokes, and gestures for assistive technologies to get to the error messages in a form. Explain that several groups of users require error messages that communicate the problem and suggest fixes where possible. Show how successful form interaction becomes difficult or impossible without such error messages.
