### ISSUE TITLE
[Content Author Module 6: Multimedia] Categorization of description of visual information

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-curricula#569]
>identify different approaches for providing descriptions of visual information, including:
> * integrated (speakers describe the relevant information)
> * narrative
>   * included in the main audio track of an alternative version of the video
>   * provided in a separate audio track or text file (if supported by the media player)”

I don’t think this separation works. The first one could be considered “narrative” and the text file not. What’s wrong with the simple 3 bullets at https://www.w3.org/WAI/media/av/description/#introduction ?

Also need to edit this under “Teaching Ideas for Topic”

**Comment by daniel-montalvo** [comment]
Thanks @shawna-slh

I was trying to simplify these three bullets. 

To me, descriptions provided through text files can be also narrative, as they are not integrated in the main audio. Whether the description is provided through a text file or through a separate audio track in the video is much of a process issue rather than a categorization issue.

Please have a look at #573 

Do you think this improves what we have previously?
b

**Comment by daniel-montalvo** [comment]
Hey @shawna-slh 
Live draft is updated at:
https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/multimedia/#topic-description-of-visual-information

**Comment by shawna-slh** [comment]
> identify different approaches for providing descriptions of visual information, including:
> * integrated — speakers describe the relevant information
> * narrative — included in the main audio track of an alternative version of the video
> * provided in a separate audio track or text file — (if supported by the media player

…
> Define narrative descriptions as those included in the main audio of an alternative version of the video.
…

Hey Daniel. Sorry but this use of "narrative description" does not work. The other 2 bullets could be considered 'narrative' as well.

> … is much of a process issue rather than a categorization issue

I’ve spent quite a bit of thought on this. Every categorization I come up with seems problematic. (possibly “integrated” or “separate”; however, not sure that might be confusing, too?) I’m not understanding why you think it’s important to categorize 3 bullets?

Let’s say I am a writer on a team creating a new video and we’re discussing description… First decision is whether description is integrated or separate. If separate, next decision is whether it is audio added to the main audio track and provided in an alternative version of the video, or provided in a text file or as a separate audio track.

I think a writer and other content creator would need to understand these options in order to decide which is best for the video content and then how to write the descriptions.

> I was trying to simplify these three bullets.

Maybe:
* integrated — the main speaker(s) provide description integrated in their speaking
* alternative video — a different speaker provides description that is included in the main audio track of an alternative version of the video
* separate file — the description is provided in a separate audio track or text file (if supported by the media player)

**Comment by daniel-montalvo** [comment]
Thanks @shawna-slh 

I was under the impression that if a description is integrated then it's not narrative. I'd say it's not narrative because it is part of the main audio of the video, it is no longer an ad hoc alternative.

If we consider that integrated descriptions can also be narrative, then we need to further discuss how to present this in the LOs.

+1 to changing "Define narrative descriptions as those included in the main audio of an alternative version of the video". That's inaccurate irrespective of the above, as you can provide a narrative description via a text file that syncs with the main audio of the video. Not sure how you can provide a narrative description that is spoken by the speakers on the main audio of the video, though.

We would probably need to either:

- look for a better definition of "narrative descriptions", or simply
- having a teaching idea on showing examples of different types of description and discussing with students pros and cons, and drop the ideaw of defining description (as it seems problematic)

**Comment by daniel-montalvo** [comment]
Categorization for different types of description is tricky. For context, see comments above in this issue.

In the Media Guide, Description, [Introduction](https://www.w3.org/WAI/media/av/description/), We have

<blockquote>

- integrated into the main script and recording (which works well for some training videos, yet not most stories)
- narration added to the main audio track and provided in an alternative version of the video (for stories)
- provided in a text file or as a separate audio track (if supported by the media player)

</blockquote>

But "provided in a text file or as a separate track" can be also narrative, since it would not be integrated in the main audio of the video.

What I think we need in a curricula for teaching content authors is to make a clear distinction between "integrated" versus "not integrated" description:

- if you plan ahead you can integrate the description for some videos.
- if you don't integrate descriptions, you'll have to add them at a later phase via an additional audio track or a text file that syncs with the main audio of the video
- at that stage, it is likely that you'll have to outsource the description creation

Updated draft at
https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/multimedia/#topic-description-of-visual-information

This deviates a bit from what we have in the media guide but I think it is worthy.

Do people agree?

**Comment by shawna-slh** [comment]
Hey @daniel-montalvo I took a pass at how we might want to update the Media resource: https://deploy-preview-190--wai-media-guide.netlify.app/media/av/description/#introduction

And I put it on the EOWG agenda for this Friday (as previously approved by the chairs).

Perhaps in the curricula you do want a simpler 1-bullet-level list?

**Comment by daniel-montalvo** [comment]
Thanks for these updates @shawna-slh 

I appreciate you taking this as a priority, so I devoted some time today to take another pass at
[Topic: Description of Visual Information](https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/multimedia/#topic-description-of-visual-information)

It now reads:

<blockquote>

* ...
* utilize integrated descriptions where possible &mdash; the main speaker(s) provide description integrated in their speaking
* identify different approaches for providing separate descriptions, including:
  * an alternative video file where authors include description in the audio of the video
  * a text or audio file that syncs with the main audio of the video &mdash; if supported by the media player

</blockquote>

I still see the two items in separate description as a sub list, but I don't feel strongly.

Happy to discuss in EOWG tomorrow in combination with your updates to the media resource if you feel comfortable with this.

**Comment by shawna-slh** [comment]
[EOWG minutes 15 July](https://www.w3.org/2022/07/15-eo-minutes#t01) -- notes the categorization of "integrated" and "separate" doesn't work for the technical implementation, the speakers, and flow, the process. Shawn will work on three bullets clearer....

**Comment by shawna-slh** [comment]
OK, here's an updated straw proposal for the [media resource, description introduction](https://www.w3.org/WAI/media/av/description/#introduction). It's much wordier, yet hopefully clear!

Depending on the type of video and on the media player functionality, description can be:
- **integrated**
  - one video with one audio track
  - the main speaker(s) provide description included in their speaking
  - usually best for most training videos, yet not most stories
- **separate video**
  - two videos - one without description, one with description
  -  the video with description has it included in a single audio track
  - description is usually by a different speaker so it is easily distinguishable from the main audio content
- **separate file**
  - one video with main audio track, **_and_**
  - description is provided in a separate audio track **_or_** a timed text file
  - must be supported by the media player

**Comment by daniel-montalvo** [comment]
Thanks much @shawna-slh 

See one comment below. 

> Depending on the type of video and on the media player functionality, description can be:
> 
> * **integrated**
>   
>   * one video with one audio track
>   * the main speaker(s) provide description included in their speaking
>   * usually best for most training videos, yet not most stories

To me this is confusing. Putting this in the very first place emphasizes the audio track, instead of emphasizing that the description needs to be integrated in the script, even before recording.

If we need to say this explicitly, I would put it in the second place. Like in:

> * **integrated**
>   
>   * the main speaker(s) provide description included in their speaking
>   * one video with one audio track
>   * usually best for most training videos, yet not most stories

> * **separate video**
>   
>   * two videos - one without description, one with description
>   * the video with description has it included in a single audio track
>   * description is usually by a different speaker so it is easily distinguishable from the main audio content
> * **separate file**
>   
>   * one video with main audio track, **_and_**
>   * description is provided in a separate audio track **_or_** a timed text file
>   * must be supported by the media player

**Comment by shawna-slh** [comment]
hey @daniel-montalvo I agree that the main point of integrated is that it's included by the speaker. I swapped the order for parallelism with the other bullets -- so the first sub-bullet in all say how many videos there are... I'll rethink.

Also, note that sometimes there isn't a script (e.g., presentations where speakers have an outline and slides, but not a detailed script)... but probably good to add that anyway, since usually there is. :)

**Comment by shawna-slh** [comment]
EOWG, please comment on [revised proposal for media resource, description introduction](https://deploy-preview-191--wai-media-guide.netlify.app/media/av/description/#introduction)

**Comment by bakkenb** [comment]
I like these updates. All three options are more clearly stated. I also agree with the order they have been placed.

**Comment by daniel-montalvo** [comment]
See [Current curricula wording](https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/multimedia/#topic-description-of-visual-information)

See [22 July EO discussion](https://www.w3.org/2022/07/22-eo-minutes.html#t01)

People seemed OK with current curricula wording. Curricula and multimedia resource have different audiences, so as long as there is overall alignment in terminology and guidance we are good with current wording.

**Comment by eoncins** [comment]
Hello @shawna-slh and @daniel-montalvo thanks a lot for the clarification. 

I agree with the updated version, into the three main bullets maybe it would be worth to provide a more clear definition in the title to make them easier to understand.

- The first bullet point is "integrated" (what?) maybe "integrated audio file"
- The second bullet is "separate video" maybe "separate video file"
- The third bullet is "separate file" maybe "separate audio or text file"

For editor's discretion.

**Comment by daniel-montalvo** [comment]
Thanks @eoncins 

See
https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/multimedia/#topic-description-of-visual-information

> * The first bullet point is "integrated" (what?) maybe "integrated audio file"

    I'd say integrated in the main video, as the description is supposed to be included in the script and verbalized by the main speaker

> * The second bullet is "separate video" maybe "separate video file"

    I'd say "alternative video".  The description is provided in a different video, but at the same time is integrated in the main audio of that different video. This is the trickiest one for me to explain. The word "separate" 
was dropped. See [15 July EOWG meeting minutes](https://www.w3.org/2022/07/15-eo-minutes.html#t01) for context.

> * The third bullet is "separate file" maybe "separate audio or text file"

    Added "separate audio or text file"

**Comment by bruce-usab** [comment]
> EOWG decided against this approach

I have been following some of the conversation I think that is all fine.  One suggestion I almost made was to use <q>descriptive narration</q> instead of <q>description</q> &mdash; but then I realized the guidance includes the case where description is provided by a timed text file.  Consequently, I cannot think of any improvements, and IMHO the present categorizations are very helpful.

Thanks again to EOWG for the excellent resource materials!

**Comment by shawna-slh** [comment]
Another pass that keeps the same approach with some wording tweaks:

[Media resource with wording in context](https://deploy-preview-194--wai-media-guide.netlify.app/media/av/description/#introduction)
> * **integrated description** — description is included in the main speakers’ scripts
> * **alternative video** — description is included in a separate video
> * **separate file** — description is in a timed text file or synched audio file; must be supported by the media player
>
> [+] More about types of description:
...

[Content Authors Curricula wording in context](https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/multimedia/#topic-description-of-visual-information)
> * integrated description — authors include description in the main speakers’ scripts
> * alternative video — authors include description in a separate script and the description is included in the audio track of an alternative video
> * separate file — authors include description in a separate script and the description is provided in a timed text file or synched audio file; must be supported by the media player

**Comment by daniel-montalvo** [comment]
Thanks everyone for your +1 on this.

See [Updated draft](https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/multimedia/#topic-description-of-visual-information)

**Comment by shawna-slh** [comment]
/me will update in media resource, then close this issue.
