### ISSUE TITLE
[Content Author Module 5: Data Tables] [medium] Learning to deconstruct complex data tables

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-curricula#606]
One thing that we often stress regarding data tables is that making them simpler is usually a good plan. Might this be worth adding as a learning outcome?

**Comment by daniel-montalvo** [comment]
Thanks for this suggestion, @iadawn 

This is now more explicitly in
https://content-author-modules--wai-curricula.netlify.app/curricula/content-author-modules/data-tables/#topic-table-data-cells

Learning outcome for topic

> split complex tables into simpler ones to make the information easier to understand

As well as corresponding teaching ideas and assessment.
I think this addresses your concerns. I will mark this as resolved. Feel free to comment if you think otherwise.
