### ISSUE TITLE
[Unit 4][Topic]: Standards and Guidelines - Slight cleanup of W3C/WAI language

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-curricula#88]
In this topic, under the Learning Outcomes, the acronyms W3C and WAI are used in three of the bullets. I worry it will be a little confusing to those trying to determine what is to be learned and how to teach it. I would like to see this clarified or simplified somehow. 

For example, does the third bullet need the "W3C/WAI" in front of the word guidelines in this statement at all? Maybe use "Refer to the inclusion of **_the various_** guidelines in different policies and standards internationally."

Question of whether we should way WAI updates/develops these guidelines, or if we should say the W3C updates/develops these guidelines. Will people understand exactly what WAI is? Has this been defined earlier in the curricula? (sorry I can't quite remember)

**Comment by daniel-montalvo** [comment]
Thanks for this.

There is not a clear definition of the acronym WAI as Web Accessibility Initiative, so based on this comment I should add this the first time it appears in the curricula.

These phrases have been changed to "W3C accessibility standards" as it is the choice in the resource [W3C accessibility standards overview](https://www.w3.org/WAI/standards-guidelines/). There are the following exceptions:

> ### Topic: Standards and Guidelines
> 
> ...
>
> Go through the milestones in WAI standard's development. Use the resource [How WAI Develops Accessibility Standards through the W3C Process](https://www.w3.org/wai/standards-guidelines/w3c-process) 


For this one, I think we should keep the WAI since we use this in the title of this resource ourselves.

> #### Teaching Ideas
> 
> * ...
> * Explain that WAI develops these standards following the W3C process, with involvement of representation of people with disabilities, industry, public, and research bodies, and individual experts.
> * ...

Once again we are referring to the resource called [How WAI develops accessibility standards ...](https://www.w3.org/WAI/standards-guidelines/w3c-process/)

Is it now clearer?

**Comment by bakkenb** [comment]
Yes, I think this could be much better. Would like to see it all in place to see if there still seems to be a chance of confusion or inconsistency.

**Comment by shawna-slh** [comment]
+1 to latest implementation using "W3C accessibility standards"

**Comment by shawna-slh** [comment]
When I teach about the guidelines/standards, I **briefly** explain what W3C is, and what WAI does.

Maybe good to add that?
